services:
  - type: web
    name: bot-hawk-esports
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: PUBG_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000

databases:
  - name: bot-redis
    plan: free
  - name: bot-postgres
    databaseName: hawk_esports_bot
    user: hawk_bot_user
    plan: free