# 游뚿 Regras de Alerta - Bot Hawk Esports
# Alertas cr칤ticos para monitoramento

groups:
  - name: hawk-bot-alerts
    rules:
      # Bot offline
      - alert: BotOffline
        expr: up{job="hawk-bot"} == 0
        for: 1m
        labels:
          severity: critical
          service: discord-bot
        annotations:
          summary: "Bot Hawk Esports est치 offline"
          description: "O bot Discord n칚o est치 respondendo h치 mais de 1 minuto."

      # Alto uso de CPU
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alto uso de CPU detectado"
          description: "CPU usage est치 acima de 80% por mais de 5 minutos."

      # Alto uso de mem칩ria
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alto uso de mem칩ria detectado"
          description: "Uso de mem칩ria est치 acima de 85% por mais de 5 minutos."

      # Disco cheio
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Espa칞o em disco baixo"
          description: "Menos de 10% de espa칞o livre no disco."

      # Redis offline
      - alert: RedisOffline
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis est치 offline"
          description: "Servi칞o Redis n칚o est치 respondendo h치 mais de 2 minutos."

      # Muitos erros no bot
      - alert: HighErrorRate
        expr: rate(bot_errors_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: discord-bot
        annotations:
          summary: "Alta taxa de erros no bot"
          description: "Bot est치 gerando mais de 0.1 erros por segundo."

      # Lat칡ncia alta do bot
      - alert: HighBotLatency
        expr: bot_command_duration_seconds > 5
        for: 2m
        labels:
          severity: warning
          service: discord-bot
        annotations:
          summary: "Alta lat칡ncia nos comandos"
          description: "Comandos do bot est칚o demorando mais de 5 segundos para responder."

      # Prometheus n칚o consegue fazer scrape
      - alert: PrometheusTargetDown
        expr: up == 0
        for: 1m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "Target do Prometheus est치 down"
          description: "Target {{ $labels.instance }} n칚o est치 respondendo ao scraping."

  - name: discord-api-alerts
    rules:
      # Rate limit do Discord
      - alert: DiscordRateLimit
        expr: discord_rate_limit_hits_total > 10
        for: 1m
        labels:
          severity: warning
          service: discord-api
        annotations:
          summary: "Rate limit do Discord atingido"
          description: "Bot est치 sendo limitado pela API do Discord."

      # Falha na conex칚o com Discord
      - alert: DiscordConnectionFailed
        expr: discord_connection_status == 0
        for: 30s
        labels:
          severity: critical
          service: discord-api
        annotations:
          summary: "Conex칚o com Discord falhou"
          description: "Bot perdeu conex칚o com a API do Discord."

  - name: system-health-alerts
    rules:
      # Container reiniciando muito
      - alert: ContainerRestarting
        expr: rate(container_start_time_seconds[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container reiniciando frequentemente"
          description: "Container {{ $labels.name }} est치 reiniciando muito frequentemente."

      # Load average alto
      - alert: HighLoadAverage
        expr: node_load1 > 2
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Load average alto"
          description: "Load average de 1 minuto est치 acima de 2.0."