# 📊 Configuração Prometheus - Bot Hawk Esports
# Monitoramento completo do sistema

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hawk-bot-monitor'
    environment: 'production'

# Configuração de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Regras de alerta
rule_files:
  - "alert_rules.yml"

# Configuração de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Bot Discord metrics
  - job_name: 'hawk-bot'
    static_configs:
      - targets: ['bot:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: /metrics

# Configurações de armazenamento
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Configurações de performance
remote_write:
  - url: "http://localhost:9090/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500